### ISSUE TITLE
Add image save function

### ISSUE THREAD

**Issue by andrewbenton** [BenjaminSchaaf/daffodil#32]
The example in the README.md makes use of a save function which doesn't exist, so the example on the front page doesn't compile.

**Comment by BenjaminSchaaf** [comment]
Yep, that's what the `// Note: Saving does not yet work` is for. Currently saving in only implemented for headers in `daffodil.bmp`

**Comment by BenjaminSchaaf** [comment]
Fixed as of 67c4ea4e7883e70ea135e322cff2a2e06a9c507b. Removing notice from README
