### ISSUE TITLE
Dub build

### ISSUE THREAD

**Issue by wilsonjord** [BenjaminSchaaf/daffodil#38]
Dub version 1.0.0
DMD version 2.073.2

dub fetch daffodil
dub build daffodil

I get the following error:
\dub\packages\daffodil-0.1.2\daffodil\source\daffodil\util\range.d(56,1): Error: class daffodil.util.range.ImageRangeObject!(Range).ImageRangeObject interface function 'int opApply(scope int delegate(PixelData))' is not implemented

**Comment by BenjaminSchaaf** [comment]
I've made a new release, version 0.1.3, that contains the fix for this. I fixed this a while ago but hadn't bothered releasing a new version.
